### ISSUE TITLE
Remove that repo

### ISSUE THREAD

**Issue by elemoine** [LI3DS/fdw-rosbag#3]
@mbredif to avoid confusion and code duplication I would like to remove that repo. Can you please move all your developments to fdw-li3ds? Thanks.

**Comment by mbredif** [comment]
OK, I will do that

**Comment by elemoine** [comment]
@mbredif I am going to port your pcpoint to fdw-li3ds (and it's going to be error-prone). When done I will delete this repo, so I'd recommend that you keep a copy of the repo somewhere.

**Comment by elemoine** [comment]
Deleting the repo now… 5 4 3 2…
